name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: cd-repo
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Spring Boot Application
        run: mvn clean package -DskipTests

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Tag Docker Image
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          716525550340.dkr.ecr.ap-south-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Docker Image
        run: |
          docker push 716525550340.dkr.ecr.ap-south-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host:13.233.155.238
          username:ec2-user
          key: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEArpXEkPY31tJpJAZ7n9O4OhiuGw6Z5Z7Mw/aTbyHVfAaKQH3tzSmj
USHPSUzAnrOY/TBK4aeqD2cO1Jbjbf508F1S5ts9YyFmW2cACowNdFnk37ZLQhtQnxDdZU
DhO65EO1SnntGgaTIpwSrGXI155P4tc6ZeKXBt8MN2HlNvfcR/NI0YGrd9srA1MzhXyf65
iYw65OtITAPkmf82B7oDJdoSUxUtlL1ncLpMlqyIpe2bxzKtX+XvVfIQ6TqXEd5YaUiCXf
6RjkVvh6AuTfjMgmLjHThT9jLefi1l8OtcwlW1Pi56apHZfoJVLXQVMIHiZ+fk+ATrORvK
MYh6EIbtNAH9hykctWkwfpsx/mef2AOCOhIyrwJvqvnbgWcG3WgsVUKAFBGfz5Y3U0iIc9
5q1PuZUU/lstYfMTKwzUj48sbBSYIxbGeZ9S3TdD3pU5NIbao2hk9xZcgBvD1X8fnaDB7A
G1UCcbsPKrg5fRvRVefy48BlmFwfr4LWGMm6IkrVhdON/hspgQ4/8cbtH4xv3xuFFpL044
DGbR6RYY3VqpYbT9XRlF+lT8VEfi3xHyZWltfNHLOEwYptWxisiixExFOlMjSyZAawNZ6O
ySDn5MNqV/b8ySKYKzg2AzybrJ7vHvhAhAh5JmJnpuv8MjhjHtLbnye34P1f5sQ+Xb30xK
UAAAdQB0vlggdL5YIAAAAHc3NoLXJzYQAAAgEArpXEkPY31tJpJAZ7n9O4OhiuGw6Z5Z7M
w/aTbyHVfAaKQH3tzSmjUSHPSUzAnrOY/TBK4aeqD2cO1Jbjbf508F1S5ts9YyFmW2cACo
wNdFnk37ZLQhtQnxDdZUDhO65EO1SnntGgaTIpwSrGXI155P4tc6ZeKXBt8MN2HlNvfcR/
NI0YGrd9srA1MzhXyf65iYw65OtITAPkmf82B7oDJdoSUxUtlL1ncLpMlqyIpe2bxzKtX+
XvVfIQ6TqXEd5YaUiCXf6RjkVvh6AuTfjMgmLjHThT9jLefi1l8OtcwlW1Pi56apHZfoJV
LXQVMIHiZ+fk+ATrORvKMYh6EIbtNAH9hykctWkwfpsx/mef2AOCOhIyrwJvqvnbgWcG3W
gsVUKAFBGfz5Y3U0iIc95q1PuZUU/lstYfMTKwzUj48sbBSYIxbGeZ9S3TdD3pU5NIbao2
hk9xZcgBvD1X8fnaDB7AG1UCcbsPKrg5fRvRVefy48BlmFwfr4LWGMm6IkrVhdON/hspgQ
4/8cbtH4xv3xuFFpL044DGbR6RYY3VqpYbT9XRlF+lT8VEfi3xHyZWltfNHLOEwYptWxis
iixExFOlMjSyZAawNZ6OySDn5MNqV/b8ySKYKzg2AzybrJ7vHvhAhAh5JmJnpuv8MjhjHt
Lbnye34P1f5sQ+Xb30xKUAAAADAQABAAACAAshEXuDMpqPZbPt9N4Cp10OuzSO2PkmBxwb
4Rilwb/rA8+qJ2lbdOWEX/wmeCX1wXQsaq2ZXFIoie2746ocnTRAYrtEMRTbaXS8q2hAts
/atigbrQ79AkXtk4tzmBgPmxpkIl5RsyXZlIdTlHsMar+SA3A6pAiEugFt2F8FBxevmcNO
FkIHvevQ50dJWXFPO2EdDxkONZjg66b0eauC7FXyoZXpxPLVIx2wxpaZT4myTKqlXJ9/Hy
Ntr63KdhxlveGSRXs78eftnbc52xHN4S2To7I2Z8XLRtsoxjWWL17VC114JYYbH4/8u3TP
EFW8BeSFSBeWaq9Eif5f2pYon8DEd258+9Po3s65Eu5wk5ync8alK42AlKMfVBcXrue7qR
0KsRNpERbYBeRlxe+wBlX672eeSoPUwyJUWZqEGl0JCRvph0HtaIqKPQDm1sJYSgAO/v5d
hnTr88cEfZBzajTwh/o4/L3Gz9PC3kjfa0GK6JYWcrJILxpTTcJTLK44aUSrASrQRZqF8I
GfULi17OaU7Xi9XVGqjF8Lk/vcv7hT7KPW/LlcZRTFEIzJhLp6tf/LeR7T4qSQqw4+cKrs
hWf2BYNw9/xvY4NmKPEnvNQ6YQkBexpdhx+IR6rDJF67lMP31cLS/K2vZEkAgXvQZ7olAa
XPKhTYKQPKax3jA3UJAAABAQCS5glzyBk4JFW7pB2XWSXpRDj/azht+xWUDxdZ+vwJu4PQ
2aogx9/yONm8JgpdWsULcXB/OvDCCoUMr+f0jK7XoFPaewfelyqdkuXEcKEET4oM/71/xH
JeXQdiM8oqJMcmHW085sL4gBT496tCQra0u2V6QbejSpk7GjmqLXh6ADJTRwTpmsvY54rJ
uWeKCCRUcuEPpqUlPFAMmWBMQK2ixzu0gO6QZnOmfkm3jS0XtqnJ5B82XfSZQi9nczqfwk
PFSC157dPkB89gbIvcBER3F1/00rtR0P+EFT8nVCeDihqJNtqAmREb+lGWGPSwKsGx7fHS
6Y2MZ12ZkaMbZKxUAAABAQD188JGiE0QgnAzNa0P0sw5EWzi58mZIkbICLuw3RftCbi9Hw
zhOTqF1mSy+syjY5oG0iO+/Tez3K8/dSQAYB+7B+UK6I6ENPhR5H1Y1lQO1CorI7If+DfM
1afDKw3g/hCWP2F6OC7xZBOuggRlmgFqvp2ZOVl5BGNXqlQ2y5WmZyuvW5ObkR+KvlQdeP
Cdgl+b+KnM2yUQURz90QXZYOuWmpZG1tTOKugkiNU9VR/dUEXhGNTNdd0O/cCJCD4ivaUp
eQnv/Jn+/tueybTzWm1qoZMgcfiFatBldWTf9htyx/AyqxiwJNCJzrI3ZMyFv2HPyNma2b
g6b9WvOuI9UyxJAAABAQC1t6FJz+YXCfdP4QSbvRmS/T4PboSlkzQ/Wj7LIqcw2KM+JxGw
eDxMH+QsGxU9kd6EvXZZ43bP59e5PQxXLEdurX4aGkDDjDVLHi9i9TyjZKmlNx0DEuGDVT
LemnU3t8rF1LS1pKLOOiL9hQ5x6j70mDOlL9jOlf0kcM3I7o5KidR6wsPf6ZXjOBw9keat
wLgsts2SJj4WYPaa93Ms0HkaUED8+61BJcVrMCA99I7UkazVvg0qD+gYAbGKTQA9xuGtfZ
yuM/L4g7p/8MAAwpSEaaS2bSqPg1p2JpDM/XIrV1vVuz+ES6dyit5h/aoPInycYsPI5TSe
fJAFgDlE9P19AAAAFnlvdXItZW1haWxAZXhhbXBsZS5jb20BAgME
-----END OPENSSH PRIVATE KEY-----

          port: 22
          script: |
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 716525550340.dkr.ecr.ap-south-1.amazonaws.com

            docker pull 716525550340.dkr.ecr.ap-south-1.amazonaws.com/cd-repo:latest

            docker stop cd-app || true

            docker rm cd-app || true

            docker run -d \
              --name cd-app \
              -p 8080:8080 \
              --restart unless-stopped \
              716525550340.dkr.ecr.ap-south-1.amazonaws.com/cd-repo:latest

            docker image prune -f